// Concatenates the Sugarcube-generated CSS (design tokens) and the CUBE CSS
// layers + components into a single `assets/styles.css`, wrapped in cascade
// layers so the ordering is explicit and predictable.
//
// Run via `npm run css` (after `sugarcube generate`). The output is committed so
// the deployed app never needs Node — it just serves the static file.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const base = "assets/css";
const read = (p) => readFileSync(join(base, p), "utf8");

// Read every *.css directly inside a directory, alphabetically.
const readDir = (dir) =>
  readdirSync(join(base, dir))
    .filter((f) => f.endsWith(".css"))
    .sort()
    .map((f) => read(join(dir, f)))
    .join("\n");

// Components live one level deeper: components/<name>/<name>.css
const readComponents = () => {
  const dir = join(base, "components");
  if (!existsSync(dir)) return "";
  return readdirSync(dir)
    .sort()
    .flatMap((name) => {
      const file = join("components", name, `${name}.css`);
      return existsSync(join(base, file)) ? [read(file)] : [];
    })
    .join("\n");
};

const layer = (name, css) => `@layer ${name} {\n${css}\n}\n`;

let out = "/* Generated by build-css.mjs — do not edit. Source: tokens/ + sugarcube CLI. */\n";
out += "@layer tokens, global, compositions, utilities, components, exceptions;\n\n";
out += layer("tokens", `${read("tokens.css")}\n${existsSync(join(base, "tokens.dark.css")) ? read("tokens.dark.css") : ""}`);
out += layer("global", read("cube/global/global.css"));
out += layer("compositions", readDir("cube/compositions"));
out += layer("utilities", readDir("cube/utilities"));
out += layer("components", readComponents());

// App-specific overrides / exceptions live here, outside the generated files so
// they survive regeneration.
if (existsSync("assets/css/app.css")) {
  out += layer("exceptions", readFileSync("assets/css/app.css", "utf8"));
}

writeFileSync("assets/styles.css", out);
console.log(`Wrote assets/styles.css (${out.length} bytes)`);
